"use client";

import { memo } from "react";

function AnalyticsTab({ overviewMetrics, onRefresh }: { overviewMetrics: any; onRefresh: () => void }) {
  const total = overviewMetrics?.totalConversations || 1;
  return <div className="space-y-6 max-w-7xl mx-auto">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-xl font-bold text-white">Analytics & Insights</h1><p className="text-xs text-slate-400">Measure support workload, AI resolution, handoffs, and knowledge-base coverage.</p></div><button type="button" onClick={onRefresh} className="rounded border border-slate-700 bg-slate-900 px-3 py-2 text-xs font-medium text-slate-200 hover:bg-slate-800">Refresh data</button></div>
    <div className="grid grid-cols-1 md:grid-cols-4 gap-4">{[["Conversations", overviewMetrics?.totalConversations || 0, "text-blue-400"],["AI Resolution Rate", `${overviewMetrics?.resolutionRate ?? 0}%`, "text-emerald-400"],["Human Handoffs", overviewMetrics?.handoffs || 0, "text-amber-400"],["Open Tickets", overviewMetrics?.openTickets || 0, "text-purple-400"]].map(([label,value,color]) => <div key={label as string} className="rounded-xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs text-slate-400">{label}</p><p className={`mt-2 text-3xl font-bold ${color}`}>{value}</p></div>)}</div>
    <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
      <div className="rounded-xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs font-medium text-slate-400">AI resolution</p><div className="mt-4 flex items-center gap-5"><div className="grid h-24 w-24 place-items-center rounded-full" style={{ background: `conic-gradient(#10b981 ${(overviewMetrics?.resolutionRate ?? 0) * 3.6}deg, #1e293b 0deg)` }}><div className="grid h-16 w-16 place-items-center rounded-full bg-slate-900 text-center"><span className="text-lg font-bold text-white">{overviewMetrics?.resolutionRate ?? 0}%</span></div></div><p className="max-w-[160px] text-xs leading-relaxed text-slate-400">Share of conversations resolved without waiting for a human agent.</p></div></div>
      <div className="rounded-xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs font-medium text-slate-400">Human workload</p><p className="mt-3 text-3xl font-bold text-amber-400">{overviewMetrics?.handoffs || 0}</p><p className="mt-1 text-xs text-slate-500">conversations currently requiring agent attention</p><div className="mt-4 h-2 overflow-hidden rounded bg-slate-800"><div className="h-full rounded bg-amber-400" style={{ width: `${Math.min(100, ((overviewMetrics?.handoffs || 0) / total) * 100)}%` }} /></div></div>
      <div className="rounded-xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs font-medium text-slate-400">Knowledge readiness</p><p className="mt-3 text-3xl font-bold text-blue-400">{overviewMetrics?.totalKnowledgeSources || 0}</p><p className="mt-1 text-xs text-slate-500">sources indexed into {overviewMetrics?.totalDocumentChunks || 0} searchable chunks</p><div className="mt-4 flex gap-1">{[1,2,3,4,5,6,7,8,9,10].map((level) => <span key={level} className={`h-2 flex-1 rounded ${level <= Math.min(10, overviewMetrics?.totalKnowledgeSources || 0) ? "bg-blue-400" : "bg-slate-800"}`} />)}</div></div>
    </div>
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <div className="rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-sm font-semibold text-white">Conversation states</h2><div className="mt-4 space-y-3">{Object.entries(overviewMetrics?.stateBreakdown || {}).map(([state,count]) => { const width=Math.max(3,(Number(count)/total)*100); const labels:Record<string,string>={AI_ACTIVE:"AI active",WAITING_FOR_AGENT:"Waiting for agent",AGENT_ACTIVE:"Agent active",RESOLVED:"Resolved"}; const colors:Record<string,string>={AI_ACTIVE:"bg-blue-500",WAITING_FOR_AGENT:"bg-amber-400",AGENT_ACTIVE:"bg-violet-500",RESOLVED:"bg-emerald-500"}; return <div key={state}><div className="mb-1 flex justify-between text-xs text-slate-400"><span>{labels[state] || state.replaceAll("_"," ")}</span><span>{String(count)} · {Math.round((Number(count)/total)*100)}%</span></div><div className="h-2 overflow-hidden rounded bg-slate-800"><div className={`h-full rounded ${colors[state] || "bg-slate-500"}`} style={{width:`${width}%`}} /></div></div>; })}</div></div>
      <div className="rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-sm font-semibold text-white">Detected languages</h2><div className="mt-4 space-y-3">{overviewMetrics?.languageBreakdown?.length ? overviewMetrics.languageBreakdown.map((entry:any) => { const share=Math.round((entry.count/total)*100); return <div key={entry.language} className="rounded bg-slate-800/60 px-3 py-2 text-xs"><div className="flex justify-between"><span className="uppercase text-slate-300">{entry.language}</span><span className="font-semibold text-white">{entry.count} · {share}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded bg-slate-700"><div className="h-full rounded bg-cyan-400" style={{width:`${share}%`}} /></div></div>; }) : <p className="text-xs text-slate-500">No conversation data yet.</p>}</div></div>
    </div>
    <div className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-white">Questions needing attention</h2><span className="rounded bg-amber-950 px-2 py-1 text-[10px] font-semibold text-amber-300">{overviewMetrics?.unansweredQuestions?.length || 0} open</span></div><div className="mt-3 space-y-2">{overviewMetrics?.unansweredQuestions?.length ? overviewMetrics.unansweredQuestions.map((question:any) => <div key={question.id} className="flex items-start justify-between gap-4 rounded border border-amber-900/50 bg-amber-950/30 px-3 py-3 text-xs text-amber-100"><span>{question.question}</span><span className="shrink-0 text-[10px] text-amber-400">{question.timestamp ? new Date(question.timestamp).toLocaleString() : ""}</span></div>) : <p className="text-xs text-slate-500">No unanswered questions or pending handoffs.</p>}</div></div>
  </div>;
}

export default memo(AnalyticsTab);
