import { boolean, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { conversations, customers, organizations, tickets, users } from "./schema.js";

export const anonymousVisitors = pgTable("anonymous_visitors", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(), visitorKeyHash: text("visitor_key_hash").notNull(), memoryEnabled: boolean("memory_enabled").default(true).notNull(), privacyConsentVersion: text("privacy_consent_version"), privacyConsentAt: timestamp("privacy_consent_at"), firstSeenAt: timestamp("first_seen_at").defaultNow().notNull(), lastSeenAt: timestamp("last_seen_at").defaultNow().notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({ visitorKeyUnique: uniqueIndex("anonymous_visitor_key_unique").on(table.organizationId, table.visitorKeyHash), visitorOrgIdx: index("anonymous_visitor_org_idx").on(table.organizationId, table.lastSeenAt) }));

export const visitorConversations = pgTable("visitor_conversations", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(), visitorId: uuid("visitor_id").references(() => anonymousVisitors.id, { onDelete: "cascade" }).notNull(), conversationId: uuid("conversation_id").references(() => conversations.id, { onDelete: "cascade" }).notNull(), createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => ({ conversationUnique: uniqueIndex("visitor_conversation_unique").on(table.organizationId, table.conversationId), visitorHistoryIdx: index("visitor_conversation_history_idx").on(table.organizationId, table.visitorId, table.createdAt) }));

export const visitorMemories = pgTable("visitor_memories", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(), visitorId: uuid("visitor_id").references(() => anonymousVisitors.id, { onDelete: "cascade" }).notNull(), type: text("type").notNull(), summary: text("summary").notNull(), status: text("status").default("active").notNull(), sourceConversationId: uuid("source_conversation_id").references(() => conversations.id, { onDelete: "set null" }), metadata: jsonb("metadata").default({}).notNull(), expiresAt: timestamp("expires_at"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({ visitorMemoryIdx: index("visitor_memory_idx").on(table.organizationId, table.visitorId, table.status, table.updatedAt) }));

export const customerPortalAccounts = pgTable("customer_portal_accounts", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(), customerId: uuid("customer_id").references(() => customers.id, { onDelete: "cascade" }).notNull(), status: text("status").default("pending_verification").notNull(), emailVerifiedAt: timestamp("email_verified_at"), lastLoginAt: timestamp("last_login_at"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({ orgCustomerPortalUnique: uniqueIndex("customer_portal_org_customer_unique").on(table.organizationId, table.customerId), portalAccountOrgIdx: index("customer_portal_account_org_idx").on(table.organizationId, table.status) }));

export const customerPortalMagicLinks = pgTable("customer_portal_magic_links", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(), accountId: uuid("account_id").references(() => customerPortalAccounts.id, { onDelete: "cascade" }).notNull(), tokenHash: text("token_hash").notNull().unique(), purpose: text("purpose").default("login").notNull(), expiresAt: timestamp("expires_at").notNull(), usedAt: timestamp("used_at"), createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => ({ portalMagicLinkIdx: index("customer_portal_magic_link_idx").on(table.organizationId, table.accountId, table.expiresAt) }));

export const customerPortalSessions = pgTable("customer_portal_sessions", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(), accountId: uuid("account_id").references(() => customerPortalAccounts.id, { onDelete: "cascade" }).notNull(), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at").notNull(), revokedAt: timestamp("revoked_at"), createdAt: timestamp("created_at").defaultNow().notNull(), lastSeenAt: timestamp("last_seen_at").defaultNow().notNull(),
}, (table) => ({ portalSessionIdx: index("customer_portal_session_idx").on(table.organizationId, table.accountId, table.expiresAt) }));

export const customerPortalVisitorLinks = pgTable("customer_portal_visitor_links", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(), accountId: uuid("account_id").references(() => customerPortalAccounts.id, { onDelete: "cascade" }).notNull(), visitorId: uuid("visitor_id").references(() => anonymousVisitors.id, { onDelete: "cascade" }).notNull(), consentVersion: text("consent_version").notNull(), consentedAt: timestamp("consented_at").defaultNow().notNull(), revokedAt: timestamp("revoked_at"), createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => ({ portalVisitorUnique: uniqueIndex("customer_portal_visitor_unique").on(table.organizationId, table.accountId, table.visitorId), portalVisitorIdx: index("customer_portal_visitor_idx").on(table.organizationId, table.visitorId) }));

export const ticketSlaPolicies = pgTable("ticket_sla_policies", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(), priority: text("priority").notNull(), firstResponseMinutes: integer("first_response_minutes").notNull(), resolutionMinutes: integer("resolution_minutes").notNull(), enabled: boolean("enabled").default(true).notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({ orgPrioritySlaUnique: uniqueIndex("ticket_sla_org_priority_unique").on(table.organizationId, table.priority) }));

export const ticketCaseMetadata = pgTable("ticket_case_metadata", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(), ticketId: uuid("ticket_id").references(() => tickets.id, { onDelete: "cascade" }).notNull(), firstResponseDueAt: timestamp("first_response_due_at"), resolutionDueAt: timestamp("resolution_due_at"), firstRespondedAt: timestamp("first_responded_at"), resolvedAt: timestamp("resolved_at"), waitingSince: timestamp("waiting_since"), slaPausedAt: timestamp("sla_paused_at"), totalPausedSeconds: integer("total_paused_seconds").default(0).notNull(), escalationLevel: integer("escalation_level").default(0).notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({ ticketCaseUnique: uniqueIndex("ticket_case_ticket_unique").on(table.organizationId, table.ticketId), ticketCaseSlaIdx: index("ticket_case_sla_idx").on(table.organizationId, table.resolutionDueAt) }));

export const ticketCaseEvents = pgTable("ticket_case_events", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(), ticketId: uuid("ticket_id").references(() => tickets.id, { onDelete: "cascade" }).notNull(), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), type: text("type").notNull(), fromValue: text("from_value"), toValue: text("to_value"), metadata: jsonb("metadata").default({}).notNull(), createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => ({ ticketCaseEventIdx: index("ticket_case_event_idx").on(table.organizationId, table.ticketId, table.createdAt) }));

export const calendarConnections = pgTable("calendar_connections", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }), provider: text("provider").notNull(), externalAccountId: text("external_account_id"), encryptedCredentials: text("encrypted_credentials"), status: text("status").default("active").notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({ calendarConnectionIdx: index("calendar_connection_idx").on(table.organizationId, table.userId, table.provider) }));

export const meetingTypes = pgTable("meeting_types", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(), name: text("name").notNull(), slug: text("slug").notNull(), description: text("description"), durationMinutes: integer("duration_minutes").notNull(), bufferBeforeMinutes: integer("buffer_before_minutes").default(0).notNull(), bufferAfterMinutes: integer("buffer_after_minutes").default(0).notNull(), minimumNoticeMinutes: integer("minimum_notice_minutes").default(60).notNull(), maxFutureDays: integer("max_future_days").default(60).notNull(), meetingProvider: text("meeting_provider").default("calendar").notNull(), enabled: boolean("enabled").default(true).notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({ meetingTypeSlugUnique: uniqueIndex("meeting_type_slug_unique").on(table.organizationId, table.slug) }));

export const availabilityRules = pgTable("availability_rules", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(), meetingTypeId: uuid("meeting_type_id").references(() => meetingTypes.id, { onDelete: "cascade" }), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }), weekday: integer("weekday").notNull(), startMinute: integer("start_minute").notNull(), endMinute: integer("end_minute").notNull(), timezone: text("timezone").default("Europe/Berlin").notNull(), enabled: boolean("enabled").default(true).notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({ availabilityRuleIdx: index("availability_rule_idx").on(table.organizationId, table.meetingTypeId, table.userId, table.weekday) }));

export const bookings = pgTable("bookings", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(), meetingTypeId: uuid("meeting_type_id").references(() => meetingTypes.id, { onDelete: "restrict" }).notNull(), assignedUserId: uuid("assigned_user_id").references(() => users.id, { onDelete: "set null" }), customerId: uuid("customer_id").references(() => customers.id, { onDelete: "set null" }), conversationId: uuid("conversation_id").references(() => conversations.id, { onDelete: "set null" }), guestEmail: text("guest_email"), guestName: text("guest_name"), startsAt: timestamp("starts_at").notNull(), endsAt: timestamp("ends_at").notNull(), timezone: text("timezone").notNull(), status: text("status").default("confirmed").notNull(), providerEventId: text("provider_event_id"), meetingUrl: text("meeting_url"), createdBy: text("created_by").default("system").notNull(), idempotencyKey: text("idempotency_key"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({ bookingIdempotencyUnique: uniqueIndex("booking_idempotency_unique").on(table.organizationId, table.idempotencyKey), bookingTimeIdx: index("booking_time_idx").on(table.organizationId, table.assignedUserId, table.startsAt, table.endsAt) }));

export const bookingEvents = pgTable("booking_events", {
  id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(), bookingId: uuid("booking_id").references(() => bookings.id, { onDelete: "cascade" }).notNull(), type: text("type").notNull(), actorType: text("actor_type").notNull(), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), metadata: jsonb("metadata").default({}).notNull(), createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => ({ bookingEventIdx: index("booking_event_idx").on(table.organizationId, table.bookingId, table.createdAt) }));
