import { Router } from "express";
import authRouter from "./auth.js";
import organizationsRouter from "./organizations.js";
import assistantsRouter from "./assistants.js";
import assistantVersionsRouter from "./assistantVersions.js";
import knowledgeRouter from "./knowledge.js";
import knowledgeIntelligenceRouter from "./knowledgeIntelligence.js";
import knowledgeCollectionsRouter from "./knowledgeCollections.js";
import knowledgeRevisionsRouter from "./knowledgeRevisions.js";
import conversationsRouter from "./conversations.js";
import ticketsRouter from "./tickets.js";
import customersRouter from "./customers.js";
import agentsRouter from "./agents.js";
import analyticsRouter from "./analytics.js";
import widgetRouter from "./widget.js";
import widgetPrivacyRouter from "./widgetPrivacy.js";
import adminSettingsRouter from "./adminSettings.js";
import mailServerSettingsRouter from "./mailServerSettings.js";
import employeeDirectoryRouter from "./employeeDirectory.js";
import notificationsRouter from "./notifications.js";
import toolsRouter from "./tools.js";
import platformAdminRouter from "./platformAdmin.js";
import visitorMemoryRouter from "./visitorMemory.js";
import customerPortalRouter from "./customerPortal.js";
import customerPortalAttachmentsRouter from "./customerPortalAttachments.js";
import schedulingRouter from "./scheduling.js";
import calendarOAuthRouter from "./calendarOAuth.js";
import webhooksRouter from "./webhooks.js";
import integrationConnectionsRouter from "./integrationConnections.js";
import integrationSyncRouter from "./integrationSync.js";
import integrationInboundRouter from "./integrationInbound.js";
import attachmentsRouter from "./attachments.js";
import storageRouter from "./storage.js";
import { registerWebhookDomainBridge } from "../services/webhookDomainBridge.js";
import { registerIntegrationSyncBridge } from "../services/integrationSyncBridge.js";
import { registerBookingEmailNotificationBridge } from "../services/bookingEmailNotificationBridge.js";

registerWebhookDomainBridge();
registerIntegrationSyncBridge();
registerBookingEmailNotificationBridge();

const apiRouter = Router();

apiRouter.use("/v1/auth", authRouter);
apiRouter.use("/v1/organizations", organizationsRouter);
apiRouter.use("/v1/assistants", assistantsRouter);
apiRouter.use("/v1/assistants", assistantVersionsRouter);
apiRouter.use("/v1/knowledge", knowledgeRouter);
apiRouter.use("/v1/knowledge-intelligence", knowledgeIntelligenceRouter);
apiRouter.use("/v1/knowledge-collections", knowledgeCollectionsRouter);
apiRouter.use("/v1/knowledge-revisions", knowledgeRevisionsRouter);
apiRouter.use("/v1/conversations", conversationsRouter);
apiRouter.use("/v1/tickets", ticketsRouter);
apiRouter.use("/v1/customers", customersRouter);
apiRouter.use("/v1/agents", agentsRouter);
apiRouter.use("/v1/analytics", analyticsRouter);
apiRouter.use("/v1/notifications", notificationsRouter);
apiRouter.use("/v1/widget/privacy", widgetPrivacyRouter);
apiRouter.use("/v1/widget", widgetRouter);
apiRouter.use("/v1/customer-portal", customerPortalAttachmentsRouter);
apiRouter.use("/v1/customer-portal", customerPortalRouter);
apiRouter.use("/v1/scheduling", schedulingRouter);
apiRouter.use("/v1/calendar-oauth", calendarOAuthRouter);
apiRouter.use("/v1/webhooks", webhooksRouter);
apiRouter.use("/v1/integrations/zendesk/inbound", integrationInboundRouter);
apiRouter.use("/v1/integrations/sync", integrationSyncRouter);
apiRouter.use("/v1/integrations", integrationConnectionsRouter);
apiRouter.use("/v1/admin/mail-server", mailServerSettingsRouter);
apiRouter.use("/v1/admin/employees", employeeDirectoryRouter);
apiRouter.use("/v1/admin", adminSettingsRouter);
apiRouter.use("/v1/platform-admin", platformAdminRouter);
apiRouter.use("/v1/tools", toolsRouter);
apiRouter.use("/v1/visitor-memory", visitorMemoryRouter);
apiRouter.use("/v1/attachments", attachmentsRouter);
apiRouter.use("/v1/storage", storageRouter);

export default apiRouter;
