"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { BarChart3, Bot, Building2, GitBranch, KeyRound, RefreshCw, Save, Shield, TestTube2 } from "lucide-react";
import { api } from "@/lib/api";

type Section = "quotas" | "ai-models" | "api-keys" | "github" | "organization" | "security" | "audit-log";
const models = ["gpt-4o-mini", "gpt-4o", "gpt-3.5-turbo", "nvidia-mistral", "nvidia/llama-3.1-8b-instruct"];
const nav: { id: Section; label: string; icon: typeof Bot }[] = [
  { id: "quotas", label: "Kontingente", icon: BarChart3 }, { id: "ai-models", label: "KI-Modelle", icon: Bot },
  { id: "api-keys", label: "API-Schlüssel", icon: KeyRound }, { id: "github", label: "GitHub", icon: GitBranch },
  { id: "organization", label: "Organisation", icon: Building2 }, { id: "security", label: "Sicherheit", icon: Shield }, { id: "audit-log", label: "Änderungsprotokoll", icon: BarChart3 },
];

const Input = ({ value, onChange, type = "text", placeholder, min, max }: any) => <input type={type} value={value ?? ""} min={min} max={max} placeholder={placeholder} onChange={e => onChange(type === "number" ? Number(e.target.value) : e.target.value)} className="w-full rounded border p-2" />;
const Field = ({ label, children }: any) => <label className="block text-sm font-medium text-slate-700"><span className="mb-1 block">{label}</span>{children}</label>;

export default function SettingsClient({ initialSection }: { initialSection: Section }) {
  const [data, setData] = useState<any>(); const [form, setForm] = useState<any>({}); const [rules, setRules] = useState<any[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [logs, setLogs] = useState<any[]>([]); const [usage, setUsage] = useState<any>();
  const dirty = useMemo(() => JSON.stringify(form) !== JSON.stringify(data?.settings || {}) || JSON.stringify(rules) !== JSON.stringify(data?.rules || []), [form, rules, data]);
  const change = (key: string, value: unknown) => setForm((current: any) => ({ ...current, [key]: value }));
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await api.get("/admin/settings"); setData(response.data); setForm(response.data.settings); setRules(response.data.rules); if (initialSection === "audit-log") setLogs((await api.get("/admin/settings/audit-logs")).data); if (initialSection === "api-keys") setUsage((await api.get("/admin/settings/usage?days=7")).data); } catch (e: any) { setError(e.response?.data?.error || "Einstellungen konnten nicht geladen werden."); } finally { setLoading(false); } }, [initialSection]);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { if (!data || saving) return; setSaving(true); setError(""); const path = initialSection === "quotas" ? "/admin/settings/quotas" : initialSection === "ai-models" ? "/admin/settings/models" : initialSection === "api-keys" ? "/admin/settings/api-keys" : initialSection === "github" ? "/admin/settings/github" : "/admin/settings/organization"; try { const response = await api.put(path, initialSection === "ai-models" ? { ...form, rules } : form); const settings = response.data.settings || data.settings; setData((current: any) => ({ ...current, settings, rules })); setForm(settings); setNotice("Änderungen gespeichert"); } catch (e: any) { setError(e.response?.data?.error || "Speichern fehlgeschlagen."); } finally { setSaving(false); } };
  const test = async (path: string, payload: any, success: string) => { try { const response = await api.post(path, payload); setNotice(response.data.valid ? success : "Verbindung abgelehnt"); } catch (e: any) { setError(e.response?.data?.error || "Verbindungstest fehlgeschlagen."); } };
  if (loading) return <main className="min-h-screen bg-slate-50 p-8"><div className="h-96 animate-pulse rounded-xl bg-slate-200" /></main>;
  return <main className="min-h-screen bg-slate-50 text-slate-900"><div className="mx-auto flex max-w-6xl flex-col gap-8 p-6 md:flex-row md:p-10"><aside className="w-52 shrink-0"><p className="mb-5 text-sm font-semibold text-slate-500">PLATTFORMVERWALTUNG</p>{nav.map(({ id, label, icon: Icon }) => <Link key={id} href={`/admin/settings/${id}`} className={`mb-1 flex items-center gap-2 rounded-lg px-3 py-2 text-sm ${id === initialSection ? "bg-slate-900 text-white" : "hover:bg-slate-200"}`}><Icon size={16} />{label}</Link>)}</aside><section className="min-w-0 flex-1"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold">{nav.find(item => item.id === initialSection)?.label}</h1><p className="text-sm text-slate-500">{data?.organization?.name}</p></div>{initialSection !== "audit-log" && <button type="button" disabled={saving || !dirty} onClick={save} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{saving ? <RefreshCw className="animate-spin" size={16} /> : <Save size={16} />}Speichern</button>}</div>{notice && <p role="status" className="mb-4 rounded bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}{error && <p role="alert" className="mb-4 rounded bg-red-50 p-3 text-sm text-red-700">{error} <button type="button" onClick={load} className="underline">Erneut versuchen</button></p>}<div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">{initialSection === "quotas" && <Quotas form={form} change={change} />}{initialSection === "ai-models" && <Models form={form} change={change} rules={rules} setRules={setRules} />}{initialSection === "api-keys" && <Keys form={form} change={change} usage={usage} test={test} />}{initialSection === "github" && <GitHub form={form} change={change} test={test} />}{initialSection === "organization" && <Organization form={form} change={change} />}{initialSection === "security" && <Security form={form} change={change} />}{initialSection === "audit-log" && <Audit logs={logs} />}</div></section></div></main>;
}

function Quotas({ form, change }: any) { return <div className="grid gap-4"><Field label="Tägliches Tokenbudget"><Input type="number" min="1000" max="100000000" value={form.dailyTokenBudget ?? 100000} onChange={(v: number) => change("dailyTokenBudget", v)} /></Field><Field label="Widget-Anfragen pro Minute"><Input type="number" min="1" max="100000" value={form.widgetRequestsPerMinute ?? 60} onChange={(v: number) => change("widgetRequestsPerMinute", v)} /></Field></div>; }
function Models({ form, change, rules, setRules }: any) { return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-3">{[["Primärmodell", "primaryModel"], ["Fallback-Modell", "fallbackModel"], ["Modell für einfache Anfragen", "simpleModel"]].map(([label, key]) => <Field key={key} label={label}><select value={form[key] || "gpt-4o-mini"} onChange={e => change(key, e.target.value)} className="w-full rounded border p-2">{models.map(model => <option key={model}>{model}</option>)}</select></Field>)}</div><Field label={`Temperatur: ${Number(form.temperature ?? 0.2).toFixed(1)}`}><input className="w-full" type="range" min="0" max="2" step="0.1" value={form.temperature ?? 0.2} onChange={e => change("temperature", Number(e.target.value))} /></Field><Field label="Max. Tokens"><Input type="number" min="32" max="4096" value={form.maxTokens ?? 500} onChange={(v: number) => change("maxTokens", v)} /></Field><div><div className="mb-2 flex justify-between"><b>Routingregeln</b><button type="button" onClick={() => setRules([...rules, { keywords: [], targetModel: form.primaryModel, enabled: true }])} className="text-sm text-blue-700">+ Regel</button></div>{rules.map((rule: any, index: number) => <div key={rule.id || index} className="mb-2 grid gap-2 rounded border p-2 md:grid-cols-[1fr_180px_auto]"><Input value={(rule.keywords || []).join(", ")} placeholder="Schlüsselwörter" onChange={(v: string) => setRules(rules.map((r: any, i: number) => i === index ? { ...r, keywords: v.split(",").map(x => x.trim()).filter(Boolean) } : r))} /><select value={rule.targetModel || form.primaryModel} onChange={e => setRules(rules.map((r: any, i: number) => i === index ? { ...r, targetModel: e.target.value } : r))} className="rounded border p-2">{models.map(model => <option key={model}>{model}</option>)}</select><button type="button" onClick={() => setRules(rules.filter((_: any, i: number) => i !== index))} className="text-sm text-red-700">Entfernen</button></div>)}</div></div>; }
function Keys({ form, change, usage, test }: any) { return <div className="space-y-5"><p className="text-sm text-slate-500">Gespeicherte Schlüssel werden nie erneut angezeigt. Ein leerer Wert behält den bestehenden Schlüssel.</p>{(["openai", "nvidia"] as const).map(provider => <div key={provider} className="flex gap-2"><Field label={`${provider.toUpperCase()} API Key`}><Input type="password" value={form[`${provider}Key`] || ""} placeholder={form[`${provider}KeyConfigured`] ? "•••••••• (konfiguriert)" : "Key eingeben"} onChange={(v: string) => change(`${provider}Key`, v)} /></Field><button type="button" onClick={() => test("/admin/settings/test-key", { provider, apiKey: form[`${provider}Key`] }, "Key ist gültig")} className="mt-6 inline-flex h-10 items-center gap-1 rounded border px-3 text-sm"><TestTube2 size={15} />Test</button></div>)}<Field label="Kostenwarnung pro Monat (USD)"><Input type="number" value={form.costAlertThreshold ?? 50} onChange={(v: number) => change("costAlertThreshold", v)} /></Field><p className="rounded bg-slate-50 p-3 text-sm">{usage?.message || "Nutzungsdaten werden geladen …"}</p></div>; }
function GitHub({ form, change, test }: any) { return <div className="space-y-5"><p className="text-sm text-slate-600">Für jedes neue KI-Eskalationsticket wird ein GitHub Issue angelegt. Der Token wird verschlüsselt gespeichert und nie wieder angezeigt.</p><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={form.githubIssuesEnabled === true} onChange={e => change("githubIssuesEnabled", e.target.checked)} /> GitHub Issues für KI-Eskalationen aktivieren</label><Field label="Repository (organisation/repository)"><Input value={form.githubRepository || ""} placeholder="devion-systems/support" onChange={(v: string) => change("githubRepository", v)} /></Field><div className="flex items-end gap-2"><Field label="GitHub Fine-grained Token (Issues: Read and write)"><Input type="password" value={form.githubToken || ""} placeholder={form.githubTokenConfigured ? "•••••••• (konfiguriert)" : "Token eingeben"} onChange={(v: string) => change("githubToken", v)} /></Field><button type="button" onClick={() => test("/admin/settings/github/test", { githubRepository: form.githubRepository, githubToken: form.githubToken }, "GitHub-Verbindung erfolgreich")} className="inline-flex h-10 items-center gap-1 rounded border px-3 text-sm"><TestTube2 size={15} />Test</button></div></div>; }
function Organization({ form, change }: any) { return <div className="grid gap-4"><Field label="Support-E-Mail"><Input value={form.supportEmail || ""} onChange={(v: string) => change("supportEmail", v)} /></Field><Field label="Primärsprache"><Input value={form.primaryLanguage || "de"} onChange={(v: string) => change("primaryLanguage", v)} /></Field><Field label="Fallback-Sprachen (kommagetrennt)"><Input value={(form.fallbackLanguages || []).join(", ")} onChange={(v: string) => change("fallbackLanguages", v.split(",").map(x => x.trim()).filter(Boolean))} /></Field><Field label="Widget-Logo-URL"><Input value={form.logoUrl || ""} onChange={(v: string) => change("logoUrl", v)} /></Field></div>; }
function Security({ form, change }: any) { return <div className="grid gap-6"><div className="grid gap-4"><Field label="Session-Timeout (Minuten)"><Input type="number" min="5" value={form.sessionTimeout ?? 60} onChange={(v: number) => change("sessionTimeout", v)} /></Field><Field label="API-Key-Rotation (Tage)"><Input type="number" min="1" value={form.apiKeyExpiryDays ?? 90} onChange={(v: number) => change("apiKeyExpiryDays", v)} /></Field><Field label="IP-Whitelist (eine IP pro Zeile)"><textarea className="min-h-28 w-full rounded border p-2" value={(form.ipWhitelist || []).join("\n")} onChange={e => change("ipWhitelist", e.target.value.split("\n").map(x => x.trim()).filter(Boolean))} /></Field></div><fieldset className="space-y-4 border-t pt-6"><legend className="text-base font-semibold">Active Directory</legend><p className="text-sm text-slate-600">Anmeldung über ein vorhandenes Active-Directory-Konto. Es wird ausschließlich LDAPS mit Zertifikatsprüfung verwendet.</p><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={form.activeDirectoryEnabled === true} onChange={e => change("activeDirectoryEnabled", e.target.checked)} /> Active Directory als Anmeldemethode aktivieren</label><Field label="LDAPS-URL"><Input value={form.activeDirectoryUrl || ""} placeholder="ldaps://dc01.example.internal:636" onChange={(v: string) => change("activeDirectoryUrl", v)} /></Field><Field label="Base DN"><Input value={form.activeDirectoryBaseDn || ""} placeholder="DC=example,DC=internal" onChange={(v: string) => change("activeDirectoryBaseDn", v)} /></Field><Field label="Bind DN"><Input value={form.activeDirectoryBindDn || ""} placeholder="CN=supportai-bind,OU=Service Accounts,DC=example,DC=internal" onChange={(v: string) => change("activeDirectoryBindDn", v)} /></Field><Field label="Bind-Passwort"><Input type="password" value={form.activeDirectoryBindPassword || ""} placeholder={form.activeDirectoryBindPasswordConfigured ? "•••••••• (konfiguriert)" : "Passwort eingeben"} onChange={(v: string) => change("activeDirectoryBindPassword", v)} /></Field></fieldset></div>; }
function Audit({ logs }: { logs: any[] }) { return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-2">Zeit</th><th>Aktion</th><th>IP</th></tr></thead><tbody>{logs.map(log => <tr key={log.id} className="border-b"><td className="p-2">{new Date(log.createdAt).toLocaleString()}</td><td>{log.action}</td><td>{log.ipAddress || "—"}</td></tr>)}</tbody></table></div>; }
