"use client";

import Link from "next/link";
import { cloneElement, useCallback, useEffect, useId, useMemo, useState, type ReactElement } from "react";
import { BarChart3, Bot, Building2, KeyRound, RefreshCw, Save, Shield, TestTube2 } from "lucide-react";
import { api } from "@/lib/api";

type Section = "ai-models" | "api-keys" | "organization" | "security" | "audit-log";
const models = ["gpt-4o-mini", "gpt-4o", "gpt-3.5-turbo", "nvidia-mistral", "nvidia/llama-3.1-8b-instruct"];
const nav: { id: Section; label: string; icon: typeof Bot }[] = [
  { id: "ai-models", label: "AI Models", icon: Bot }, { id: "api-keys", label: "API Keys", icon: KeyRound }, { id: "organization", label: "Organization", icon: Building2 }, { id: "security", label: "Security", icon: Shield }, { id: "audit-log", label: "Audit Log", icon: BarChart3 },
];

export default function SettingsClient({ initialSection }: { initialSection: Section }) {
  const [data, setData] = useState<any>(); const [form, setForm] = useState<any>({}); const [rules, setRules] = useState<any[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [logs, setLogs] = useState<any[]>([]); const [usage, setUsage] = useState<any>();
  const dirty = useMemo(() => (JSON.stringify(form) !== JSON.stringify(data?.settings || {}) || JSON.stringify(rules) !== JSON.stringify(data?.rules || [])), [form, rules, data]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await api.get("/admin/settings"); setData(response.data); setForm(response.data.settings); setRules(response.data.rules); if (initialSection === "audit-log") setLogs((await api.get("/admin/settings/audit-logs")).data); if (initialSection === "api-keys") setUsage((await api.get("/admin/settings/usage?days=7")).data); } catch (e: any) { setError(e.response?.data?.error || "Einstellungen konnten nicht geladen werden."); } finally { setLoading(false); } }, [initialSection]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  const change = (key: string, value: unknown) => setForm((current: any) => ({ ...current, [key]: value }));
  const save = useCallback(async () => { if (saving || !data) return; setSaving(true); setError(""); try { const path = initialSection === "ai-models" ? "/admin/settings/models" : initialSection === "api-keys" ? "/admin/settings/api-keys" : "/admin/settings/organization"; const payload = initialSection === "ai-models" ? { ...form, rules } : form; const response = await api.put(path, payload); setData((current: any) => ({ ...current, settings: response.data.settings || current.settings, rules })); setForm((current: any) => JSON.stringify(current) === JSON.stringify(form) ? response.data.settings || current : current); setNotice("Änderungen gespeichert"); window.setTimeout(() => setNotice(""), 2500); } catch (e: any) { setError(e.response?.data?.error || "Speichern fehlgeschlagen."); } finally { setSaving(false); } }, [saving, data, initialSection, form, rules]);
  useEffect(() => { if (!dirty || initialSection === "audit-log" || saving || error) return; const timer = window.setTimeout(() => { void save(); }, 2000); return () => window.clearTimeout(timer); }, [dirty, initialSection, saving, error, save]);
  const testKey = async (provider: "openai" | "nvidia") => { try { const response = await api.post("/admin/settings/test-key", { provider, apiKey: form[provider === "openai" ? "openaiKey" : "nvidiaKey"] }); setNotice(response.data.valid ? "Key ist gültig" : "Key wurde abgelehnt"); } catch (e: any) { setError(e.response?.data?.error || "Key-Test fehlgeschlagen."); } };
  if (loading) return <main className="min-h-screen bg-slate-50 p-8"><div className="mx-auto max-w-6xl animate-pulse space-y-4"><div className="h-8 w-64 rounded bg-slate-200" /><div className="h-96 rounded-xl bg-slate-200" /></div></main>;
  return <main className="min-h-screen bg-slate-50 text-slate-900"><div className="mx-auto flex max-w-6xl gap-8 p-6 md:p-10"><aside className="w-48 shrink-0"><p className="mb-5 text-sm font-semibold text-slate-500">ADMIN SETTINGS</p>{nav.map(({ id, label, icon: Icon }) => <Link key={id} href={`/admin/settings/${id}`} className={`mb-1 flex items-center gap-2 rounded-lg px-3 py-2 text-sm ${id === initialSection ? "bg-slate-900 text-white" : "hover:bg-slate-200"}`}><Icon size={16} />{label}</Link>)}</aside><section className="min-w-0 flex-1"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold">{nav.find((item) => item.id === initialSection)?.label}</h1><p className="text-sm text-slate-500">{data?.organization?.name}</p></div>{initialSection !== "audit-log" && <button type="button" disabled={saving} onClick={save} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{saving ? <RefreshCw className="animate-spin" size={16} /> : <Save size={16} />}Speichern</button>}</div>{notice && <p role="status" className="mb-4 rounded bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}{error && <p role="alert" className="mb-4 rounded bg-red-50 p-3 text-sm text-red-700">{error} <button type="button" onClick={load} className="underline">Erneut versuchen</button></p>}<div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">{initialSection === "ai-models" && <Models form={form} change={change} rules={rules} setRules={setRules} />}{initialSection === "api-keys" && <Keys form={form} change={change} testKey={testKey} usage={usage} />}{initialSection === "organization" && <Organization form={form} change={change} />}{initialSection === "security" && <Security form={form} change={change} />}{initialSection === "audit-log" && <Audit logs={logs} />}</div></section></div></main>;
}
const Field = ({ label, children }: { label: string; children: ReactElement<{ id?: string }> }) => { const id = useId(); return <div className="block text-sm font-medium text-slate-700"><label htmlFor={id} className="mb-1 block">{label}</label>{cloneElement(children, { id })}</div>; };
const select = (value: string, onChange: (value: string) => void) => <select value={value || "gpt-4o-mini"} onChange={(e) => onChange(e.target.value)} className="w-full rounded border p-2">{models.map((model) => <option key={model}>{model}</option>)}</select>;
function Models({ form, change, rules, setRules }: any) { return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Field label="Primary Model">{select(form.primaryModel, (v) => change("primaryModel", v))}</Field><Field label="Fallback Model">{select(form.fallbackModel, (v) => change("fallbackModel", v))}</Field><Field label="Simple Queries Model">{select(form.simpleModel, (v) => change("simpleModel", v))}</Field></div><Field label={`Temperature: ${Number(form.temperature ?? 0.2).toFixed(1)}`}><input className="w-full" type="range" min="0" max="2" step="0.1" value={form.temperature ?? 0.2} onChange={(e) => change("temperature", Number(e.target.value))} /></Field><Field label="Max Tokens"><input className="w-full rounded border p-2" type="number" min="32" max="4096" value={form.maxTokens ?? 500} onChange={(e) => change("maxTokens", Number(e.target.value))} /></Field><div><div className="mb-2 flex justify-between"><b>Routing Rules</b><button type="button" onClick={() => setRules([...rules, { keywords: [], targetModel: form.primaryModel, enabled: true }])} className="text-sm text-blue-700">+ Regel</button></div>{rules.map((rule: any, index: number) => <fieldset aria-label="Routing rule" key={rule.id || index} draggable onDragStart={(e) => e.dataTransfer.setData("rule", String(index))} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { const from = Number(e.dataTransfer.getData("rule")); const next = [...rules]; [next[from], next[index]] = [next[index], next[from]]; setRules(next); }} className="mb-2 grid gap-2 rounded border p-2 md:grid-cols-[1fr_180px_auto]"><input value={(rule.keywords || []).join(", ")} placeholder="Keywords, komma-getrennt" onChange={(e) => setRules(rules.map((r: any, i: number) => i === index ? { ...r, keywords: e.target.value.split(",").map((x) => x.trim()).filter(Boolean) } : r))} className="rounded border p-2" />{select(rule.targetModel, (v) => setRules(rules.map((r: any, i: number) => i === index ? { ...r, targetModel: v } : r)))}<button type="button" onClick={() => setRules(rules.filter((_: any, i: number) => i !== index))} className="text-sm text-red-700">Entfernen</button></fieldset>)}</div></div> }
function Keys({ form, change, testKey, usage }: any) { return <div className="space-y-5"><p className="text-sm text-slate-500">Gespeicherte Schlüssel werden nie erneut angezeigt. Ein leerer Wert behält den bestehenden Schlüssel.</p>{(["openai", "nvidia"] as const).map((provider) => <div key={provider} className="flex gap-2"><Field label={`${provider.toUpperCase()} API Key`}><input type="password" autoComplete="new-password" placeholder={form[`${provider}KeyConfigured`] ? "•••••••• (konfiguriert)" : "Key eingeben"} value={form[`${provider}Key`] || ""} onChange={(e) => change(`${provider}Key`, e.target.value)} className="w-full rounded border p-2" /></Field><button type="button" onClick={() => testKey(provider)} className="mt-6 inline-flex h-10 items-center gap-1 rounded border px-3 text-sm"><TestTube2 size={15} />Test</button></div>)}<Field label="Kostenwarnung pro Monat (USD)"><input className="w-full rounded border p-2" type="number" value={form.costAlertThreshold ?? 50} onChange={(e) => change("costAlertThreshold", Number(e.target.value))} /></Field><p className="rounded bg-slate-50 p-3 text-sm">{usage?.message || "Nutzungsdaten werden geladen …"}</p></div> }
function Organization({ form, change }: any) { return <div className="grid gap-4"><Field label="Support E-Mail"><input className="w-full rounded border p-2" value={form.supportEmail || ""} onChange={(e) => change("supportEmail", e.target.value)} /></Field><Field label="Primärsprache"><input className="w-full rounded border p-2" value={form.primaryLanguage || "de"} onChange={(e) => change("primaryLanguage", e.target.value)} /></Field><Field label="Fallback-Sprachen (kommagetrennt)"><input className="w-full rounded border p-2" value={(form.fallbackLanguages || []).join(", ")} onChange={(e) => change("fallbackLanguages", e.target.value.split(",").map((x) => x.trim()).filter(Boolean))} /></Field><Field label="Widget-Logo URL"><input className="w-full rounded border p-2" value={form.logoUrl || ""} onChange={(e) => change("logoUrl", e.target.value)} /></Field></div> }
function Security({ form, change }: any) { return <div className="grid gap-4"><Field label="Session Timeout (Minuten)"><input className="w-full rounded border p-2" type="number" min="5" value={form.sessionTimeout ?? 60} onChange={(e) => change("sessionTimeout", Number(e.target.value))} /></Field><Field label="API-Key-Rotation (Tage)"><input className="w-full rounded border p-2" type="number" min="1" value={form.apiKeyExpiryDays ?? 90} onChange={(e) => change("apiKeyExpiryDays", Number(e.target.value))} /></Field><Field label="IP Whitelist (eine IP pro Zeile)"><textarea className="min-h-28 w-full rounded border p-2" value={(form.ipWhitelist || []).join("\n")} onChange={(e) => change("ipWhitelist", e.target.value.split("\n").map((x) => x.trim()).filter(Boolean))} /></Field></div> }
function Audit({ logs }: { logs: any[] }) { return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-2">Zeit</th><th>Aktion</th><th>IP</th></tr></thead><tbody>{logs.map((log) => <tr key={log.id} className="border-b"><td className="p-2">{new Date(log.createdAt).toLocaleString()}</td><td>{log.action}</td><td>{log.ipAddress || "—"}</td></tr>)}</tbody></table></div> }
